<?php // CONFIG AUTOGENERATED BY THE INSTALLER

// dbData::$host = 'localhost';
// dbData::$user = 'root';
// dbData::$pass = '';
// dbData::$db = 'alumni';

// dbData::$host = 'localhost';
// dbData::$user = 'admin_alumni';
// dbData::$pass = 'B6vcT6e32g';
// dbData::$db = 'admin_alumni';

$dbData = require('domainsData.php');
$db = $dbData[$_SERVER['HTTP_HOST']];

dbData::$host = $db['host'];
dbData::$user = $db['user'];
dbData::$pass = $db['pass'];
dbData::$db = $db['name'];

_::$globals['WEB_LINK'] = ENDPOINT;
// _::$globals['WEB_LINK'] = 'http://localhost';
_::$globals['WEB_DESIGN'] = _::$globals['WEB_LINK'].'/design';
