web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./site.conf:/etc/nginx/conf.d/site.conf
        - ../src:/code
    links:
        - php
php:
    image: php:7-fpm
    volumes:
        - ../src:/code