web:
    image: nginx:latest
    ports:
        - "8787:80"
    volumes:
        - ./site.conf:/etc/nginx/conf.d/site.conf
        - ../src:/code
    links:
        - php
php:
    image: alexander171294/tandilweb:php-fpm-mysql-1.0.0
    volumes:
        - ../src:/code