<?php

// model autogenerated by model_maker.php
class cached_users_close extends table
{
    // Primary keys
    protected $primaryKeys = array('id_user_searcher', 'id_user_finded', 'cache_date');

    // fields:
    public $id_user_searcher = null;
    public $id_user_finded = null;
    public $cache_date = null;

}