<?php

// model autogenerated by model_maker.php
class chats extends table
{
    // Primary keys
    protected $primaryKeys = array('id_user_requester', 'id_user_sender');

    // fields:
    public $id_user_requester = null;
    public $id_user_sender = null;
    public $last_message_id = null;

}