<?php

// model autogenerated by model_maker.php
class codigos_externos extends table
{
    // Primary keys
    protected $primaryKeys = 'id_codigo';

    // fields:
    public $id_codigo = null;
    public $codigo_acceso = null;
    public $id_event = null;

}