<?php

// model autogenerated by model_maker.php
class codigos_externos_usados extends table
{
    // Primary keys
    protected $primaryKeys = 'id_codigo';

    // fields:
    public $id_codigo = null;
    public $id_user = null;
    public $fecha_activacion = null;

}