<?php

// model autogenerated by model_maker.php
class codigos_externos extends table
{
    // Primary keys
    protected $primaryKeys = 'id_codigo';

    // fields:
    public $id_codigo = null;
    public $codigo_acceso = null;
    public $id_event = null;

    public function getCodes($evento){
        return self::getAll('LEFT JOIN codigos_externos_usados AS ceu ON ceu.id_codigo = codigos_externos.id_codigo WHERE id_event = ?', array($evento));
    }

}