<?php

// model autogenerated by model_maker.php
class configuration extends table
{
    // Primary keys
    protected $primaryKeys = 'id_user';

    // fields:
    public $id_user = null;
    public $kms_radio = null;
    public $linkedin_autoupdate = null;

}