<?php

// model autogenerated by model_maker.php
class conversaciones extends table
{
    // Primary keys
    protected $primaryKeys = 'id_mensaje';

    // fields:
    public $id_mensaje = null;
    public $fecha = null;

}