<?php

// model autogenerated by model_maker.php
class countries extends table
{
    // Primary keys
    protected $primaryKeys = 'id_country';

    // fields:
    public $id_country = null;
    public $name = null;
    public $code = null;

}