<?php

// model autogenerated by model_maker.php
class events extends table
{
    // Primary keys
    protected $primaryKeys = 'id_event';

    // fields:
    public $id_event = null;
    public $start_date = null;
    public $end_date = null;
    public $name = null;
    public $logo = null;
    public $id_gps_record = null;
    public $url = null;
    public $radio = null;
    public $nombre_lugar = null;
    public $location_description = null;

}