<?php

// model autogenerated by model_maker.php
class events extends table
{
    // Primary keys
    protected $primaryKeys = 'id_event';

    // fields:
    public $id_event = null;
    public $start_date = null;
    public $end_date = null;
    public $name = null;
    public $logo = null;
    public $id_gps_record = null;
    public $url = null;
    public $radio = null;
    public $nombre_lugar = null;
    public $location_description = null;

    public function isFinished() {
        $dtObject= new DateTime($this->end_date);
        return ($dtObject->getTimestamp() < time());
    }

    public function startDate() {
        $date = new DateTime($this->start_date);
        return $date->format('d/m/Y H:i'); // Y-m-d H:i:s
    }

    public function endDate() {
        $date = new DateTime($this->end_date);
        return $date->format('d/m/Y H:i'); // Y-m-d H:i:s
    }

    public function startDateE() {
        $date = new DateTime($this->start_date);
        return $date->format('d/m/Y'); // Y-m-d H:i:s
    }

    public function endDateE() {
        $date = new DateTime($this->end_date);
        return $date->format('d/m/Y'); // Y-m-d H:i:s
    }

    private $oGPS;
    public function getGPSRecord() {
        if(empty($this->oGPS)) {
            $this->oGPS = new gps_data_events($this->id_gps_record);
        }
        return $this->oGPS;
    }

}