<?php

// model autogenerated by model_maker.php
class external_ticket extends table
{
    // Primary keys
    protected $primaryKeys = array('id_user', 'id_event');

    // fields:
    public $id_user = null;
    public $id_event = null;

}