<?php

// model autogenerated by model_maker.php
class friendships extends table
{
    // Primary keys
    protected $primaryKeys = array('id_user_requester', 'id_user_target');

    // fields:
    public $id_user_requester = null;
    public $id_user_target = null;
    public $is_accepted = null;
    public $date_emitted = null;
    public $is_viewed = null;
    public $is_rejected = null;

}