<?php

// model autogenerated by model_maker.php
class gps_data_events extends table
{
    // Primary keys
    protected $primaryKeys = 'id_gps_record';

    // fields:
    public $id_gps_record = null;
    public $latitude = null;
    public $longitude = null;

}