<?php

// model autogenerated by model_maker.php
class gps_data_users extends table
{
    // Primary keys
    protected $primaryKeys = array('id_gps_record', 'id_user');

    // fields:
    public $id_gps_record = null;
    public $id_user = null;

}