<?php

// model autogenerated by model_maker.php
class mensajes extends table
{
    // Primary keys
    protected $primaryKeys = 'id_mensaje';

    // fields:
    public $id_mensaje = null;
    public $id_sender = null;
    public $id_target = null;
    public $messages = null;
    public $fecha = null;
    public $is_viewed = null;

}