<?php

// model autogenerated by model_maker.php
class profile extends table
{
    // Primary keys
    protected $primaryKeys = 'id_user';

    // fields:
    public $id_user = null;
    public $headline = null;
    public $industry = null;
    public $country = null;
    public $location = null;
    public $linkedin_url = null;
    public $summary = null;
    public $current_position = null;
    public $company_name = null;

}