<?php

// model autogenerated by model_maker.php
class remember_tokens extends table
{
    // Primary keys
    protected $primaryKeys = 'id_user';

    // fields:
    public $id_user = null;
    public $unlock_key = null;
    public $request_date = null;
    public $attempts = null;

}