<?php

// model autogenerated by model_maker.php
class stands extends table
{
    // Primary keys
    protected $primaryKeys = 'id_stand';

    // fields:
    public $id_stand = null;
    public $id_event = null;
    public $name = null;
    public $logo = null;
    public $id_user_organizer = null;

}