<?php

// model autogenerated by model_maker.php
class stands_checkin extends table
{
    // Primary keys
    protected $primaryKeys = array('id_stand', 'id_user');

    // fields:
    public $id_stand = null;
    public $id_user = null;
    public $date_checkin = null;

}