<?php

// model autogenerated by model_maker.php
class stands_checkin extends table
{
    // Primary keys
    protected $primaryKeys = array('id_stand', 'id_user');

    // fields:
    public $id_stand = null;
    public $id_user = null;
    public $date_checkin = null;

    static public function getUsersOfCheckin($id_stand) {
        return users::getAllObjects('id_user', 'LEFT JOIN stands_checkin ON stands_checkin.id_stand = ? WHERE users.id_user = stands_checkin.id_user', array($id_stand));
    }

}