<?php

// model autogenerated by model_maker.php
class users extends table
{
    // Primary keys
    protected $primaryKeys = 'id_user';

    // fields:
    public $id_user = null;
    public $first_name = null;
    public $last_name = null;
    public $email = null;
    public $password = null;
    public $last_login = null;
    public $signup_date = null;
    public $linkedin_id = null;
    public $busco = null;
    public $ofrezco = null;
    public $picture_url = null;
    public $is_premium = null;
    public $salt_jwt = null;
    public $completoByO = null;
    public $receive_notifications = null;
    public $locked = null;
    public $failed_login_attempts = null;
    public $unlock_account_code = null;
    public $fcm_token = null;
    public $is_admin = null;

    public static function getByEmail($email) {
        return self::getUniqueObject('id_user', 'WHERE email = ?', array($email));
    }

    public function getFormattedSignupDate() {
        $date = new DateTime($this->signup_date);
        return $date->format('d/m/Y'); // Y-m-d H:i:s
    }

    public function getFormattedLastLogin() {
        $date = new DateTime($this->last_login);
        return $date->format('d/m/Y'); // Y-m-d H:i:s
    }

}