<?php

// model autogenerated by model_maker.php
class dispositivos extends table
{
    // Primary keys
    protected $primaryKeys = 'id_dispositivo';

    // fields:
    public $id_dispositivo = null;
    public $descripcion = null;
    public $uid_device = null;
    public $sistema_operativo = null;
    public $usuario_registrante = null;
    public $fecha_alta = null;
    public $fecha_actividad = null;
    public $habilitado = null;

}